### ISSUE TITLE
Report exception to topmost TryCatch or if verbose

### ISSUE THREAD

**Issue by brendandahl** [mozilla/spidernode#89] opened 2016-05-12 22:32 UTC
Once propagating exceptions is implemented CheckReportExternalException will need extra logic to only report the exception if this is the topmost TryCatch or if verbose reporting is enabled.

**Comment by brendandahl** [comment] 2016-05-12 22:32
Depends on #51

**Comment by ehsan** [comment] 2016-05-12 22:54
Hmm, isn't it a dupe of #51?

**Comment by ehsan** [comment] 2016-05-15 19:23
Oh, nm, I was misreading this somehow! :-)

**Closed as completed** 2016-05-15 21:52 UTC
